Neural Net on neo.csv
 

Data pre-processing

Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

Importing dataset

In [3]:
dataset = pd.read_csv('neo.csv')
X = dataset.iloc[:, 2:9].values
y = dataset.iloc[:, -1].values

Encoding categorial data

encoding independent variable

encoding orbiting_body column

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

encoding sentry_object column

In [5]:
from sklearn.preprocessing import LabelEncoder
le1= LabelEncoder()
X[:,5]=le1.fit_transform(X[:,5])

In [6]:
print(X)

[[1.0 1.1982708007 2.6794149658 ... 54839744.08284605 0 16.73]
 [1.0 0.2658 0.5943468684 ... 61438126.52395093 0 20.0]
 [1.0 0.7220295577 1.6145071727 ... 49798724.94045679 0 17.83]
 ...
 [1.0 0.0319561887 0.0714562102 ... 28400768.1610167 0 24.6]
 [1.0 0.0073207399 0.016369672 ... 68692060.5345607 0 27.8]
 [1.0 0.0398616229 0.0891332986 ... 59772130.59268528 0 24.12]]


Encoding dependent variable

In [7]:

le2 = LabelEncoder()
y = le2.fit_transform(y)

In [8]:
print(y)

[0 1 0 ... 0 0 0]


Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[ 0.         -0.41855692 -0.41855692 ...  0.11822139  0.
   2.92919472]
 [ 0.         -0.32544362 -0.32544362 ... -0.85832669  0.
   0.44176864]
 [ 0.         -0.33394526 -0.33394526 ... -1.0587696   0.
   0.51086381]
 ...
 [ 0.         -0.34531592 -0.34531592 ...  0.99492594  0.
   0.61450656]
 [ 0.         -0.15471923 -0.15471923 ...  0.03852826  0.
  -0.32173298]
 [ 0.         -0.2201943  -0.2201943  ... -0.12460938  0.
  -0.11099271]]


In [12]:
print(X_test)

[[ 0.         -0.37988826 -0.37988826 ...  0.7386474   0.
   1.06362516]
 [ 0.          0.18757484  0.18757484 ... -0.80678297  0.
  -0.94013474]
 [ 0.         -0.40187796 -0.40187796 ... -1.63750142  0.
   1.61638651]
 ...
 [ 0.          0.0403941   0.0403941  ...  0.6632239   0.
  -0.73284923]
 [ 0.         -0.4036542  -0.4036542  ... -1.64014542  0.
   1.68548168]
 [ 0.         -0.3582279  -0.3582279  ... -1.51803899  0.
   0.7526969 ]]


Building the neural net

In [13]:
nn=tf.keras.models.Sequential()

Adding input layer and first hidden layer

In [14]:
nn.add(tf.keras.layers.Dense(units=4,activation='relu'))

Adding another hidden layer

In [15]:
nn.add(tf.keras.layers.Dense(units=4,activation='relu'))

Final output layer

In [16]:
nn.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))#since the output is in binary form

Training the neural net

In [17]:
nn.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [18]:
nn.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
1988/1988 [==============================] - 8s 3ms/step - loss: 0.2881 - accuracy: 0.8978
Epoch 2/100
1988/1988 [==============================] - 5s 3ms/step - loss: 0.2049 - accuracy: 0.9028
Epoch 3/100
1988/1988 [==============================] - 5s 3ms/step - loss: 0.2003 - accuracy: 0.9028
Epoch 4/100
1988/1988 [==============================] - 7s 3ms/step - loss: 0.1978 - accuracy: 0.9028
Epoch 5/100
1988/1988 [==============================] - 6s 3ms/step - loss: 0.1949 - accuracy: 0.9028
Epoch 6/100
1988/1988 [==============================] - 5s 3ms/step - loss: 0.1926 - accuracy: 0.9058
Epoch 7/100
1988/1988 [==============================] - 5s 2ms/step - loss: 0.1909 - accuracy: 0.9105
Epoch 8/100
1988/1988 [==============================] - 5s 3ms/step - loss: 0.1903 - accuracy: 0.9108
Epoch 9/100
1988/1988 [==============================] - 5s 2ms/step - loss: 0.1899 - accuracy: 0.9110
Epoch 10/100
1988/1988 [==============================] - 5s 3ms/step - l

Predicting the Test set results

In [24]:
y_pred = nn.predict(X_test)
y_pred = (y_pred > 0.5)
print("Actual result:",y_test)
print("predicted result:",y_pred)

852/852 [==============================] - 1s 1ms/step
Actual result: [0 1 0 ... 0 0 0]
predicted result: [[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


Accuracy:

In [26]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.9128839308649224
